
java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/1.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr1 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_1.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/2.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr2 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_2.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/3.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr3 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_3.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/5.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr5 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_5.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/6.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr6 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_6.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/7.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr7 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_7.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/9.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr9 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_9.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/10.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chr10 -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_10.gz

java -Xmx32G -cp bin/triogen-0.2.0/triogen-0.2.0.jar no.uib.triogen.cmd.association.LinearModel -g /mnt/archive/MOBAGENETICS/genotypes-base/imputed/all/vcf/X.vcf.gz -gf 1 -v /mnt/work/marc/moba/trioGen/resources/targets_chrX -f /mnt/archive/helgeland/helgeland2020/sensitive/fulltriads-n24280-180919 -p tmp/phenos -pn breastmilk_duration,formula_freq_6m,pregnancy_duration,z_umbilical_chord_length,z_placenta_weight,z_bmi0,z_bmi1,z_bmi2,z_bmi3,z_bmi4,z_bmi5,z_bmi6,z_bmi7,z_bmi8,z_bmi9,z_bmi10,z_bmi11,z_mother_height,z_father_bmi -o /mnt/work/marc/moba/trioGen/tmp/lm_targets_X.gz
